name: 'Generate Structurizr Diagrams Images from DSL'
description: 'Automatically generates and updates Structurizr diagrams images on pull requests that modifies DSL.'
branding:
  icon: 'activity'
  color: 'white'
inputs:
  repo-token:
    description: 'GITHUB_TOKEN from secrets'
    required: true
  workspace-path:
    description: 'Path to the DSL file'
    required: true
    default: 'docs/workspace.dsl'
  output-path:
    description: 'Path to the generated images'
    required: true
    default: 'docs/diagrams'
  image-type:
    description: 'Type of image to generate, either png or svg'
    required: true
    default: 'svg'

runs:
  using: 'composite'
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      env:
        GITHUB_TOKEN: ${{ inputs.repo-token }}
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Setup Git
      run: git config --global --add safe.directory $PWD
      shell: bash

    - name: Generate Diagram Images
      if : ${{ inputs.image-type == 'png' }}
      run: |
        echo "Actual folder is"
        echo $PWD
        /usr/local/structurizr-cli/structurizr.sh export -workspace ${{ inputs.workspace-path }} -format plantuml -output ${{ inputs.output-path }}
        cd ${{ inputs.output-path }}
        echo 'Generating PNGs...'
        plantuml -tpng *.puml
      shell: bash

    - name: Generate Diagram Images
      if : ${{ inputs.image-type == 'svg' }}
      run: |
        echo "Actual folder is"
        echo $PWD
        /usr/local/structurizr-cli/structurizr.sh export -workspace ${{ inputs.workspace-path }} -format plantuml -output ${{ inputs.output-path }}
        cd ${{ inputs.output-path }}
        echo 'Generating SVGs...'
        plantuml -tsvg *.puml
        ls -la
      shell: bash

    - name: Check for Changes PNG
      id: check_changes_png
      if : ${{ inputs.image-type == 'png' }}
      env:
        GITHUB_TOKEN: ${{ inputs.repo-token }} 
      run: |
        git add *.png
        if git diff --staged --quiet; then
          echo "No changes to commit."
          echo "CHANGES_EXIST=false" >> $GITHUB_ENV
        else
          echo "CHANGES_EXIST=true" >> $GITHUB_ENV
          echo "Changes detected, committing..."
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          git commit -m "Update Structurizr diagrams: SVG diagrams updated"
        fi
      shell: bash

    - name: Check for Changes SVG
      id: check_changes_svg
      if : ${{ inputs.image-type == 'svg' }}
      env:
        GITHUB_TOKEN: ${{ inputs.repo-token }} 
      run: |
        git add *.svg
        if git diff --staged --quiet; then
          echo "No changes to commit."
          echo "CHANGES_EXIST=false" >> $GITHUB_ENV
        else
          echo "CHANGES_EXIST=true" >> $GITHUB_ENV
          echo "Changes detected, committing..."
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          git commit -m "Update Structurizr diagrams: SVG diagrams updated"
        fi
      shell: bash

    - name: Commit and Push Diagrams
      if: env.CHANGES_EXIST == 'true' && github.event_name  == 'pull_request'
      env:
        GITHUB_TOKEN: ${{ inputs.repo-token }} 
      run: |
        echo "Committing and pushing diagrams..."
        git push origin HEAD:${GITHUB_HEAD_REF}
      shell: bash

    - name: Commit and Push Diagrams on Push
      if: steps.check_changes.outputs.changes_exist == 'true' && github.event_name  == 'push'
      run: |
        echo "Committing and pushing diagrams..."
        git push
      shell: bash