name: 'Generate Structurizr Diagrams Images from DSL'
description: 'Automatically generates and updates Structurizr diagrams images on pull requests that modifies DSL.'
branding:
  icon: 'activity'
  color: 'white'
inputs:
  repo-token:
    description: 'GITHUB_TOKEN from secrets'
    required: true
  workspace-path:
    description: 'Path to the DSL file'
    required: true
    default: 'docs/workspace.dsl'
  output-path:
    description: 'Path to the generated images'
    required: true
    default: 'docs/diagrams'

runs:
  using: 'composite'
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      env:
        GITHUB_TOKEN: ${{ inputs.repo-token }}
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Setup Git
      run: git config --global --add safe.directory $PWD
      shell: bash

    - name: Generate Diagram Images
      run: |
        ls /usr
        ls /usr/local
        ls /usr/local/structurizr-cli
        ls /home
        ls /home/runner
        ls /home/runner/work
        /usr/local/structurizr-cli/structurizr.sh export -workspace ${{ inputs.workspace-path }} -format plantuml -output ${{ inputs.output-path }}
        cd ${{ inputs.output-path }}
        echo 'Generating PNGs...'
        plantuml -tpng *.puml
      shell: bash

    - name: Check for Changes
      id: check_changes
      run: |
        git add *.png
        if git diff --staged --quiet; then
          echo "CHANGES_EXIST=false" >> $GITHUB_ENV
        else
          echo "CHANGES_EXIST=true" >> $GITHUB_ENV
      shell: bash

    - name: Commit and Push Diagrams
      if: env.CHANGES_EXIST == 'true'
      env:
        GITHUB_TOKEN: ${{ inputs.repo-token }}
      run: |
        git commit -m "chores(C4 diagrams): Update Structurizr diagrams"
        git push origin HEAD:${GITHUB_HEAD_REF}
      shell: bash